package items.minecraft.GTNH.thaumcraft;

import items.Item;

import static register.Namespaces.THAUMCRAFT;

public class Aspects {
    public static final Item AER = new Item(THAUMCRAFT, "aer");
    public static final Item TERRA = new Item(THAUMCRAFT, "terra");
    public static final Item IGNIS = new Item(THAUMCRAFT, "ignis");
    public static final Item AQUA = new Item(THAUMCRAFT, "aqua");
    public static final Item ORDO = new Item(THAUMCRAFT, "ordo");
    public static final Item PERDITIO = new Item(THAUMCRAFT, "perditio");
    public static final Item VACUOS = new Item(THAUMCRAFT, "vacuos");
    public static final Item LUX = new Item(THAUMCRAFT, "lux");
    public static final Item TEMPESTAS = new Item(THAUMCRAFT, "tempestas");
    public static final Item MOTUS = new Item(THAUMCRAFT, "motus");
    public static final Item GELUM = new Item(THAUMCRAFT, "gelum");
    public static final Item VITREUS = new Item(THAUMCRAFT, "vitreus");
    public static final Item VICTUS = new Item(THAUMCRAFT, "victus");
    public static final Item VENENUM = new Item(THAUMCRAFT, "venenum");
    public static final Item POTENTIA = new Item(THAUMCRAFT, "potentia");
    public static final Item PERMUTATIO = new Item(THAUMCRAFT, "permutatio");
    public static final Item METALLUM = new Item(THAUMCRAFT, "metallum");
    public static final Item MORTUUS = new Item(THAUMCRAFT, "mortuus");
    public static final Item VOLATUS = new Item(THAUMCRAFT, "volatus");
    public static final Item TENEBRAE = new Item(THAUMCRAFT, "tenebrae");
    public static final Item SPIRITUS = new Item(THAUMCRAFT, "spiritus");
    public static final Item SANO = new Item(THAUMCRAFT, "sano");
    public static final Item ITER = new Item(THAUMCRAFT, "iter");
    public static final Item ALIENIS = new Item(THAUMCRAFT, "alienis");
    public static final Item PRAECANTATIO = new Item(THAUMCRAFT, "praecantatio");
    public static final Item AURAM = new Item(THAUMCRAFT, "auram");
    public static final Item VITIUM = new Item(THAUMCRAFT, "vitium");
    public static final Item LIMUS = new Item(THAUMCRAFT, "limus");
    public static final Item HERBA = new Item(THAUMCRAFT, "herba");
    public static final Item ARBOR = new Item(THAUMCRAFT, "arbor");
    public static final Item BESTIA = new Item(THAUMCRAFT, "bestia");
    public static final Item CORPUS = new Item(THAUMCRAFT, "corpus");
    public static final Item EXANIMUS = new Item(THAUMCRAFT, "exanimus");
    public static final Item COGNITO = new Item(THAUMCRAFT, "cognito");
    public static final Item SENSUS = new Item(THAUMCRAFT, "sensus");
    public static final Item HUMANUS = new Item(THAUMCRAFT, "humanus");
    public static final Item MESSIS = new Item(THAUMCRAFT, "messis");
    public static final Item PERFODIO = new Item(THAUMCRAFT, "perfodio");
    public static final Item INSTRUMENTUM = new Item(THAUMCRAFT, "instrumentum");
    public static final Item METO = new Item(THAUMCRAFT, "meto");
    public static final Item TELUM = new Item(THAUMCRAFT, "telum");
    public static final Item TUTAMEN = new Item(THAUMCRAFT, "tutamen");
    public static final Item FAMES = new Item(THAUMCRAFT, "fames");
    public static final Item LUCRUM = new Item(THAUMCRAFT, "lucrum");
    public static final Item FABRICO = new Item(THAUMCRAFT, "fabrico");
    public static final Item PANNUS = new Item(THAUMCRAFT, "pannus");
    public static final Item MACHINA = new Item(THAUMCRAFT, "machina");
    public static final Item VINCULUM = new Item(THAUMCRAFT, "vinculum");
    public static final Item STRONTIO = new Item(THAUMCRAFT, "strontio");
    public static final Item NEBRISUM = new Item(THAUMCRAFT, "nebrisum");
    public static final Item ELECTRUM = new Item(THAUMCRAFT, "electrum");
    public static final Item MAGNETO = new Item(THAUMCRAFT, "magneto");
    public static final Item RADIO = new Item(THAUMCRAFT, "radio");
    public static final Item AEQUALITAS = new Item(THAUMCRAFT, "aequalitas");
    public static final Item VESANIA = new Item(THAUMCRAFT, "vesania");
    public static final Item PRIMORDIUM = new Item(THAUMCRAFT, "primordium");
    public static final Item ASTRUM = new Item(THAUMCRAFT, "astrum");
    public static final Item GLORIA = new Item(THAUMCRAFT, "gloria");
    public static final Item TERMINUS = new Item(THAUMCRAFT, "terminus");
    public static final Item LUXURIA = new Item(THAUMCRAFT, "luxuria");
    public static final Item INFERNUS = new Item(THAUMCRAFT, "infernus");
    public static final Item SUPERBIA = new Item(THAUMCRAFT, "superbia");
    public static final Item GULA = new Item(THAUMCRAFT, "gula");
    public static final Item INVIDIA = new Item(THAUMCRAFT, "invidia");
    public static final Item DESIDIA = new Item(THAUMCRAFT, "desidia");
    public static final Item IRA = new Item(THAUMCRAFT, "ira");
    public static final Item TEMPUS = new Item(THAUMCRAFT, "tempus");
    public static final Item CAELUM = new Item(THAUMCRAFT, "caelum");
    public static final Item TABERNUS = new Item(THAUMCRAFT, "tabernus");
}
