package items;

public class Items {
    public static final Item MANUAL = new Item("player","manual");
    public static final Item NOTHING = new Item("minecraft","nothing");
    public static final Item ELECTRIC_CIRCUIT = new Item("industrial_craft_2","electric_circuit");
    public static final Item CIRCUIT_BOARD = new Item("gregtech","circuit_board");
    public static final Item RESISTOR = new Item("gregtech","resistor");
    public static final Item ONE_RED_ALLOY_WIRE = new Item("gregtech","1x_red_alloy_wire");
    public static final Item ONE_COPPER_WIRE = new Item("gregtech","1x_copper_wire");
    public static final Item VACUUM_TUBE = new Item("gregtech","vacuum_tube");
    public static final Item MOLTEN_LEAD = new Item("gregtech","molten_lead");
    public static final Item LEAD_INGOT = new Item("gregtech","lead_ingot");
    public static final Item WOOD_PLANK = new Item("gregtech","wood_plank");
    public static final Item WOOD_PULP = new Item("gregtech","wood_pulp");
    public static final Item COPPER_FOIL = new Item("gregtech","copper_foil");
    public static final Item FINE_COPPER_WIRE = new Item("gregtech","fine_copper_wire");
    public static final Item REFINED_GLUE = new Item("gregtech","refined_glue");
    public static final Item ANY_WOOD = new Item("minecraft","any_log");
    public static final Item RAW_RUBBER_DUST = new Item("gregtech","raw_rubber_dust");
    public static final Item PLANT_BALL = new Item("industrial_craft_2","plant_ball");
    public static final Item STICKY_RESIN = new Item("industrial_craft_2","sticky_resin");
    public static final Item COPPER_INGOT = new Item("gregtech","copper_ingot");
    public static final Item COAL_DUST = new Item("gregtech","coal_dust");
    public static final Item RED_ALLOY_INGOT = new Item("gregtech","red_alloy_ingot");
    public static final Item REDSTONE_DUST = new Item("minecraft","redstone_dust");
    public static final Item MOLTEN_RED_ALLOY = new Item("gregtech","molten_red_alloy");
    public static final Item STEEL_ROD = new Item("gregtech","steel_rod");
    public static final Item STEEL_INGOT = new Item("gregtech","steel_ingot");
    public static final Item IRON_DUST = new Item("gregtech","iron_dust");
    public static final Item WROUGHT_IRON_INGOT = new Item("gregtech","wrought_iron_ingot");
    public static final Item WROUGHT_IRON_DUST = new Item("gregtech","wrought_iron_dust");
    public static final Item OXYGEN_GAS = new Item("gregtech","oxygen");
    public static final Item NITROGEN_GAS = new Item("gregtech","nitrogen");
    public static final Item GLASS_DUST = new Item("gregtech","glass_dust");
    public static final Item GLASS_TUBE = new Item("gregtech","glass_tube");
    public static final Item FLINT_DUST = new Item("gregtech","flint_dust");
    public static final Item QUARTZ_SAND = new Item("gregtech","quartz_sand");
    public static final Item SAND = new Item("minecraft","sand");
    public static final Item GRAVEL = new Item("minecraft","gravel");
    public static final Item COBBLESTONE = new Item("minecraft","cobblestone");
    public static final Item FLINT = new Item("minecraft","flint");
    public static final Item ASHES = new Item("gregtech","ashes");
    public static final Item EMPTY_CELL = new Item("gregtech","empty_cell");
    public static final Item COMPRESSED_AIR = new Item("gregtech","compressed_air");
    public static final Item OXYGEN_CELL = new Item("gregtech","oxygen_cell");
    public static final Item AIR_GAS = new Item("gregtech","air");
}
