package machines;

public enum MachineConfiguration {
    None,

    ProgrammedCircuitOne,
    ProgrammedCircuitTwo,
    ProgrammedCircuitThree,
    ProgrammedCircuitFour,
    ProgrammedCircuitFive,
    ProgrammedCircuitSix,
    ProgrammedCircuitSeven,
    ProgrammedCircuitEight,
    ProgrammedCircuitNine,
    ProgrammedCircuitTen,
    ProgrammedCircuitEleven,
    ProgrammedCircuitTwelve,
    ProgrammedCircuitThirteen,
    ProgrammedCircuitFourteen,
    ProgrammedCircuitFifteen,
    ProgrammedCircuitSixteen,
    ProgrammedCircuitSeventeen,
    ProgrammedCircuitEighteen,
    ProgrammedCircuitNineteen,
    ProgrammedCircuitTwenty,
    ProgrammedCircuitTwentyOne,
    ProgrammedCircuitTwentyTwo,
    ProgrammedCircuitTwentyThree,
    ProgrammedCircuitTwentyFour,

    ProgrammedBioCircuitOne,
    ProgrammedBioCircuitTwo,
    ProgrammedBioCircuitThree,
    ProgrammedBioCircuitFour,
    ProgrammedBioCircuitFive,
    ProgrammedBioCircuitSix,
    ProgrammedBioCircuitSeven,
    ProgrammedBioCircuitEight,
    ProgrammedBioCircuitNine,
    ProgrammedBioCircuitTen,
    ProgrammedBioCircuitEleven,
    ProgrammedBioCircuitTwelve,
    ProgrammedBioCircuitThirteen,
    ProgrammedBioCircuitFourteen,
    ProgrammedBioCircuitFifteen,
    ProgrammedBioCircuitSixteen,
    ProgrammedBioCircuitSeventeen,
    ProgrammedBioCircuitEighteen,
    ProgrammedBioCircuitNineteen,
    ProgrammedBioCircuitTwenty,
    ProgrammedBioCircuitTwentyOne,
    ProgrammedBioCircuitTwentyTwo,
    ProgrammedBioCircuitTwentyThree,
    ProgrammedBioCircuitTwentyFour,

    MoldBall,

    ExtrudeShapeRod
}
